name: x64-windows Build aliyun-oss-cpp-sdk  
  
on:  
  push:  
    # branches: [ main ] 
    # tags: ['*']  

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:  
  build:  
    runs-on: windows-latest  
    steps:  
      - name: windows-latest安装zip
        id: vscheck  
        run: |  
          choco install zip

      - name: 查看VStudio的版本  
        id: vscheck  
        run: |  
          vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath  
          echo "Visual Studio installation path: ${{ steps.vscheck.outputs.installationPath }}"  
          cmake --version   
  
      - name: Clone aliyun-oss-cpp-sdk  
        run: |  
          git clone https://github.com/aliyun/aliyun-oss-cpp-sdk.git  

      - name: Cmake aliyun-oss-cpp-sdk  
        run: |  
          cd aliyun-oss-cpp-sdk  
          mkdir build  
          cd build  
          cmake ..  
      - name: Build aliyun-oss-cpp-sdk  
        run: |  
          $vsInstallPath = vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath  
          $msbuildPath = Join-Path $vsInstallPath "MSBuild\Current\Bin\MSBuild.exe"  
          cd aliyun-oss-cpp-sdk/build  
          & $msbuildPath ALL_BUILD.vcxproj  
          & $msbuildPath INSTALL.vcxproj  
  
      - name: 压缩ZIP
        run: | 
          cd aliyun-oss-cpp-sdk/build  
          zip -r sdk_build.zip .  

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            aliyun-oss-cpp-sdk/build/sdk_build.zip
          token: ${{ secrets.GITHUB_TOKEN }}
